name: Build and Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'splendor-server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Install dependencies
        working-directory: splendor-server
        run: pnpm install --frozen-lockfile

      - name: Build server
        working-directory: splendor-server
        run: pnpm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and save as tar
        uses: docker/build-push-action@v5
        with:
          context: ./splendor-server
          file: ./splendor-server/Dockerfile
          push: false
          tags: splendor-server-image:latest
          outputs: type=docker,dest=image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-docker-image
          path: image.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: server-docker-image

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy image to server
        run: scp image.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/root/splendor-server/

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/splendor-server
            mkdir -p logs
            docker-compose logs > logs/backup-$(date +%Y%m%d-%H%M%S).log || true
            find logs -name "backup-*.log" -mtime +7 -delete
            docker-compose down || true
            docker load < image.tar
            docker-compose up -d
            echo "Waiting for server service to start..."
            sleep 10
            if ! curl -s http://localhost:3001 > /dev/null; then
              echo "Server service is not responding!"
              docker-compose logs
              exit 1
            fi
            rm image.tar
            docker system prune -f --volumes
            echo "✅ Server deployment completed successfully!"
