name: Deploy Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP << 'ENDSSH'
            cd /root/splendor-server
            
            # 保存最新日志
            mkdir -p logs
            docker-compose logs > logs/backup-$(date +%Y%m%d-%H%M%S).log || true

            # 清理7天前的日志
            find logs -name "backup-*.log" -mtime +7 -delete

            # 拉取最新代码
            git pull

            # 停止容器
            docker-compose down

            # 清理所有未使用的构建缓存
            docker builder prune -f --filter until=24h

            # 清理未使用的镜像
            docker image prune -a -f --filter until=24h

            # 重新构建和启动服务
            docker-compose up -d --build

            # 等待服务启动并检查
            echo "Waiting for server service to start..."
            sleep 10
            
            if ! curl -s http://localhost:3001 > /dev/null; then
              echo "Server service is not responding!"
              docker-compose logs
              exit 1
            fi

            # 部署成功后进行全面清理
            echo "Cleaning up Docker system..."
            docker system prune -f --volumes
            
            echo "Server deployment completed successfully!"
          ENDSSH 